INSERT INTO
  holidays

VALUES
  (default, );


-- JANUARY

New Years Day – Jan 1
National Hangover Day - Jan 1
NATIONAL BUFFET DAY – Jan 2
NATIONAL CREAM PUFF DAY – Jan 2
NATIONAL PERSONAL TRAINER AWARENESS DAY – Jan 2
NATIONAL SCIENCE FICTION DAY – Jan 2
NATIONAL THANK GOD IT’S MONDAY DAY – First Monday in Jan
NATIONAL CHOCOLATE COVERED CHERRY DAY – Jan 3
NATIONAL DRINKING STRAW DAY – Jan 3
NATIONAL FRUITCAKE TOSS DAY – Jan 3
NATIONAL SPAGHETTI DAY – Jan 4
NATIONAL TRIVIA DAY – Jan 4
National Bird Day – Jan 5
NATIONAL WHIPPED CREAM DAY – Jan 5
NATIONAL BEAN DAY – Jan 6

NATIONAL SHORTBREAD DAY – Jan 6

National Bobblehead Day – Jan 7
NATIONAL TEMPURA DAY – Jan 7
NATIONAL ARGYLE DAY – Jan 8
NATIONAL BUBBLE BATH DAY – Jan 8
NATIONAL ENGLISH TOFFEE DAY – Jan 8
NATIONAL JOYGERM DAY – Jan 8

NATIONAL APRICOT DAY – Jan 9
NATIONAL STATIC ELECTRICITY DAY – Jan 9
-- NATIONAL CLEAN OFF YOUR DESK DAY – Second Monday in Jan
NATIONAL BITTERSWEET CHOCOLATE DAY – Jan 10
NATIONAL CUT YOUR ENERGY COSTS DAY – Jan 10
SAVE THE EAGLES DAY – Jan 10
NATIONAL HUMAN TRAFFICKING AWARENESS DAY – Jan 11
NATIONAL MILK DAY – Jan 11
NATIONAL STEP IN A PUDDLE AND SPLASH YOUR FRIENDS DAY – Jan 11
NATIONAL CURRIED CHICKEN DAY – Jan 12
NATIONAL MARZIPAN DAY – Jan 12
NATIONAL PHARMACIST DAY – Jan 12
NATIONAL PEACH MELBA DAY – Jan 13
NATIONAL RUBBER DUCKY DAY – Jan 13

STEPHEN FOSTER MEMORIAL DAY – Jan 13
NATIONAL DRESS UP YOUR PET DAY – Jan 14
NATIONAL HOT PASTRAMI SANDWICH DAY – Jan 14
RATIFICATION DAY – Jan 14

NATIONAL HAT DAY – Jan 15
NATIONAL STRAWBERRY ICE CREAM DAY – Jan 15
NATIONAL FIG NEWTON DAY – Jan 16
NATIONAL NOTHING DAY – Jan 16
NATIONAL RELIGIOUS FREEDOM DAY – Jan 16

-- MARTIN LUTHER KING JR. DAY – Third Monday in Jan

National Hot Buttered Rum Day – Jan 17
NATIONAL PEKING DUCK DAY – Jan 18
NATIONAL WINNIE THE POOH DAY – Jan 18
NATIONAL POPCORN DAY – Jan 19

NATIONAL BUTTERCRUNCH DAY – Jan 20
NATIONAL CHEESE LOVER’S DAY – Jan 20
NATIONAL DISC JOCKEY DAY – Jan 20
NATIONAL GRANOLA BAR DAY – Jan 21
NATIONAL HUGGING DAY – Jan 21
SQUIRREL APPRECIATION DAY – Jan 21
NATIONAL BLONDE BROWNIE DAY – Jan 22
NATIONAL HANDWRITING DAY – Jan 23
NATIONAL PIE DAY – Jan 23
Beer Can Appreciation Day – Jan 24
National Compliment Day – Jan 24
NATIONAL PEANUT BUTTER DAY – Jan 24
NATIONAL IRISH COFFEE DAY – Jan 25
National Opposite Day – Jan 25

NATIONAL PEANUT BRITTLE DAY – Jan 26
NATIONAL SPOUSES DAY – Jan 26
NATIONAL CHOCOLATE CAKE DAY – Jan 27

NATIONAL BLUEBERRY PANCAKE DAY – Jan 28
NATIONAL FUN AT WORK DAY – Jan 28
NATIONAL KAZOO DAY – Jan 28
-- National Seed Swap Day – Last Saturday in Jan
NATIONAL CORN CHIP DAY – Jan 29
NATIONAL PUZZLE DAY – Jan 29
NATIONAL CROISSANT DAY – Jan 30

BACKWARD DAY – Jan 31
INSPIRE YOUR HEART WITH ART DAY – Jan 31


-- Feb

National Baked Alaska Day – Feb 1
NATIONAL FREEDOM DAY – Feb 1
National Serpent Day – Feb 1
NATIONAL GROUNDHOG DAY – Feb 2
National Heavenly Hash Day – Feb 2
National Carrot Cake Day – Feb 3
NATIONAL THE DAY THE MUSIC DIED DAY – Feb 3
National Wear Red Day – Feb 6
NATIONAL CREATE A VACUUM DAY – Feb 4
National Homemade Soup Day – Feb 4th
NATIONAL THANK A MAILMAN DAY – Feb 4
SHOWER WITH A FRIEND DAY – Feb 5
NATIONAL WEATHERPERSON’S DAY – Feb 5
NATIONAL FROZEN YOGURT DAY – Feb 6
NATIONAL LAME DUCK DAY – Feb 6
NATIONAL FETTUCCINE ALFREDO DAY – Feb 7

NATIONAL SEND A CARD TO A FRIEND DAY – Feb 7
NATIONAL BOY SCOUTS DAY – Feb 8
NATIONAL KITE FLYING DAY – Feb 8
NATIONAL BAGEL AND LOX DAY – Feb 9
NATIONAL PIZZA DAY – Feb 9
NATIONAL TOOTHACHE DAY – Feb 9
NATIONAL CREAM CHEESE BROWNIE DAY – Feb 10

NATIONAL UMBRELLA DAY – Feb 10
NATIONAL DON’T CRY OVER SPILLED MILK DAY – Feb 11

NATIONAL MAKE A FRIEND DAY – Feb 11
NATIONAL PEPPERMINT PATTY DAY – Feb 11
NATIONAL SHUT-IN VISITATION DAY – Feb 11
NATIONAL WHITE SHIRT DAY/ WHITE T-SHIRT DAY – Feb 11
NATIONAL PLUM PUDDING DAY – Feb 12
NATIONAL TORTELLINI DAY – Feb 13
-- NATIONAL CLEAN OUT YOUR COMPUTER DAY – Second Monday in Feb
NATIONAL CREAM-FILLED CHOCOLATES DAY – Feb 14
NATIONAL FERRIS WHEEL DAY – Feb 14
NATIONAL ORGAN DONOR DAY – Feb 14
Valentine’s Day – Feb 14
NATIONAL GUMDROP DAY – Feb 15
SINGLES AWARENESS DAY – Feb 15
NATIONAL ALMOND DAY – Feb 16
NATIONAL DO A GROUCH A FAVOR DAY – Feb 16
National Cabbage Day – Feb 17
NATIONAL RANDOM ACTS OF KINDNESS DAY – Feb 17

NATIONAL BATTERY DAY – Feb 18
NATIONAL CRAB STUFFED FLOUNDER DAY – Feb 18
NATIONAL DRINK WINE DAY – Feb 18
NATIONAL CHOCOLATE MINT DAY – Feb 19
NATIONAL CHERRY PIE DAY – Feb 20
NATIONAL LOVE YOUR PET DAY – Feb 20
PRESIDENTS DAY – Third Monday in Feb
NATIONAL STICKY BUN DAY – Feb 21
NATIONAL COOK A SWEET POTATO DAY – Feb 22
NATIONAL MARGARITA DAY – Feb 22
NATIONAL BANANA BREAD DAY – Feb 23
NATIONAL DOG BISCUIT DAY – Feb 23

NATIONAL CHILI DAY – Feb 27
NATIONAL TORTILLA CHIP DAY – Feb 24
NATIONAL CHOCOLATE COVERED NUT DAY – Feb 25
NATIONAL CLAM CHOWDER DAY – Feb 25
NATIONAL PISTACHIO DAY – Feb 26
NATIONAL TELL A FAIRY TALE DAY – Feb 26
NATIONAL KAHLUA DAY – Feb 27
NATIONAL POLAR BEAR DAY – Feb 27
NATIONAL STRAWBERRY DAY – Feb 27
NATIONAL CHOCOLATE SOUFFLE DAY – Feb 28
NATIONAL FLORAL DESIGN DAY – Feb 28
NATIONAL PUBLIC SLEEPING DAY – Feb 28
NATIONAL TOOTH FAIRY DAY – Feb 28
RARE DISEASE DAY USA – Feb 28
-- SPAY DAY USA – Last Tuesday in Feb



-- Mar

NATIONAL FRUIT COMPOTE DAY – Mar 1
NATIONAL HORSE PROTECTION DAY – Mar 1
NATIONAL PEANUT BUTTER LOVER’S DAY – Mar 1
NATIONAL PIG DAY – Mar 1
NATIONAL BANANA CREAM PIE DAY – Mar 2
NATIONAL OLD DAY STUFF – Mar 2
NATIONAL READ ACROSS AMERICA DAY (DR. SEUSS DAY) – Mar 2
NATIONAL ANTHEM DAY – Mar 3
NATIONAL COLD CUTS DAY – Mar 3
NATIONAL I WANT YOU TO BE HAPPY DAY – Mar 3
NATIONAL MULLED WINE DAY – Mar 3
-- NATIONAL DAY OF UNPLUGGING – First Friday in Mar
-- NATIONAL EMPLOYEE APPRECIATION DAY – First Friday in Mar
-- NATIONAL SALESPERSON DAY – First Friday in Mar
NATIONAL GRAMMAR DAY – Mar 4
NATIONAL HUG A G.I. DAY – Mar 4
NATIONAL POUND CAKE DAY – Mar 4
NATIONAL ABSINTHE DAY – Mar 5
NATIONAL CHEESE DOODLE DAY – Mar 5
National Multiple Personality Day – Mar 5
NATIONAL DENTIST’S DAY – Mar 6
NATIONAL FROZEN FOOD DAY – Mar 6
NATIONAL OREO COOKIE DAY – Mar 6
NATIONAL WHITE CHOCOLATE CHEESECAKE DAY – Mar 6
NATIONAL BE HEARD DAY – Mar 7
NATIONAL CEREAL DAY – Mar 7
NATIONAL CROWN ROAST OF PORK DAY – Mar 7
National Peanut Cluster Day Mar 8
NATIONAL PROOFREADING DAY – Mar 8
NATIONAL PANCAKE DAY – IHOP – Changes yearly
NATIONAL REGISTERED DIETITIAN NUTRITIONIST DAY – Mar 12
NATIONAL BARBIE DAY – Mar 9
NATIONAL CRAB MEAT DAY – Mar 9
NATIONAL GET OVER IT DAY – Mar 9
NATIONAL MEATBALL DAY – Mar 9
NATIONAL BLUEBERRY POPOVER DAY – Mar 10
NATIONAL MARIO DAY – Mar 10
NATIONAL PACK YOUR LUNCH DAY – Mar 10
NATIONAL WOMEN and GIRLS HIV/AIDS AWARENESS DAY – Mar 10
NATIONAL JOHNNY APPLESEED DAY – Mar 11
NATIONAL OATMEAL NUT WAFFLES DAY – Mar 11

NATIONAL WORSHIP OF TOOLS DAY – Mar 11
NATIONAL GIRL SCOUT DAY – Mar 12
NATIONAL PLANT A FLOWER DAY – Mar 12

NATIONAL COCONUT TORTE DAY – Mar 13
NATIONAL EARMUFF DAY – Mar 13
NATIONAL GOOD SAMARITAN DAY – Mar 13
NATIONAL JEWEL DAY – Mar 13
NATIONAL K9 VETERANS DAY – Mar 13
NATIONAL OPEN AN UMBRELLA INDOORS DAY – Mar 13
NATIONAL NAPPING DAY – Mar 10
NATIONAL CHILDREN’S CRAFT DAY – Mar 14
NATIONAL LEARN ABOUT BUTTERFLIES DAY – Mar 14
NATIONAL PI DAY – Mar 14
NATIONAL POTATO CHIP DAY – Mar 14
EVERYTHING YOU THINK IS WRONG DAY – Mar 15
NATIONAL PEARS HELENE DAY – Mar 15
NATIONAL SHOE THE WORLD DAY – Mar 15
NATIONAL KICK BUTTS DAY – Mar 19

NATIONAL ARTICHOKE HEARTS DAY – Mar 16
NATIONAL EVERYTHING YOU DO IS RIGHT DAY – Mar 16
NATIONAL FREEDOM OF INFORMATION DAY – Mar 16
National Corned Beef and Cabbage Day – Mar 17
St. Patrick’s Day – Mar 17th
NATIONAL AWKWARD MOMENTS DAY – Mar 18
NATIONAL BIODIESEL DAY – Mar 18
NATIONAL LACY OATMEAL COOKIE DAY – Mar 18
NATIONAL SLOPPY JOE DAY – Mar 18
NATIONAL SUPREME SACRIFICE DAY – Mar 18
NATIONAL QUILTING DAY – Third Saturday in Mar
NATIONAL CERTIFIED NURSES DAY – Mar 19
NATIONAL CHOCOLATE CARAMEL DAY – Mar 19
LET’S LAUGH DAY – Mar 19
NATIONAL POULTRY DAY – Mar 19

NATIONAL NATIVE HIV/AIDS AWARENESS DAY – Mar 20
National Proposal Day – Mar 20
NATIONAL RAVIOLI DAY – Mar 20
Spring Begins – Changes Annually Mar 19 – Mar 21
NATIONAL CALIFORNIA STRAWBERRY DAY – Mar 21
NATIONAL COMMON COURTESY DAY – Mar 21
NATIONAL FRAGRANCE DAY – Mar 21
NATIONAL FRENCH BREAD DAY – Mar 21
NATIONAL SINGLE PARENTS DAY – Mar 21
NATIONAL BAVARIAN CREPES DAY – Mar 22
NATIONAL GOOF OFF DAY – Mar 22

NATIONAL CHIP AND DIP DAY – Mar 23
NATIONAL NEAR MISS DAY – Mar 23
NATIONAL MELBA TOAST DAY – Mar 23
NATIONAL PUPPY DAY – Mar 23
NATIONAL CHOCOLATE COVERED RAISIN DAY – Mar 24
NATIONAL LOBSTER NEWBURG DAY – Mar 25
NATIONAL MEDAL OF HONOR DAY – Mar 25
TOLKIEN READING DAY – Mar 25
Purple Day – Epilepsy Awareness Day – Mar 26
NATIONAL NOUGAT DAY – Mar 26
NATIONAL SPINACH DAY – Mar 26
NATIONAL JOE DAY – Mar 27
NATIONAL SPANISH PAELLA DAY – Mar 27

NATIONAL BLACK FOREST CAKE DAY – Mar 28
NATIONAL SOMETHING ON A STICK DAY – Mar 28
NATIONAL WEED APPRECIATION DAY – Mar 28
-- AMERICAN DIABETES ASSOCIATION ALERT DAY – Fourth Tuesday in Mar
NATIONAL LEMON CHIFFON CAKE DAY – Mar 29
NATIONAL MOM AND POP BUSINESS OWNERS DAY – Mar 29

-- MANATEE APPRECIATION DAY – Last Wednesday in Mar
NATIONAL DOCTORS DAY – Mar 30
NATIONAL I AM IN CONTROL DAY
NATIONAL PENCIL DAY – Mar 30
NATIONAL TAKE A WALK IN THE PARK DAY – Mar 30
NATIONAL TURKEY NECK SOUP DAY – Mar 30
NATIONAL BUNSEN BURNER DAY – Mar 31
NATIONAL CLAMS ON THE HALF SHELL DAY – Mar 31
NATIONAL TATER DAY – Mar 31

-- Apr

APRIL FOOLS DAY – Apr 1
NATIONAL ONE CENT DAY – Apr 1
NATIONAL SOURDOUGH BREAD DAY – Apr 1
NATIONAL FERRET DAY – Apr 2
NATIONAL PEANUT BUTTER AND JELLY DAY – Apr 2
NATIONAL RECONCILIATION DAY – Apr 2
NATIONAL LOVE OUR CHILDREN DAY – Apr 5
NATIONAL CHOCOLATE MOUSSE DAY – Apr 3
NATIONAL FIND A RAINBOW DAY – Apr 3
NATIONAL TWEED DAY – Apr 3
NATIONAL CHICKEN CORDON BLEU DAY – Apr 4
NATIONAL HUG A NEWSMAN DAY – Apr 4
NATIONAL SCHOOL LIBRARIAN DAY – Apr 4
NATIONAL WALK AROUND THINGS DAY – Apr 4
NATIONAL CARAMEL DAY – Apr 5
NATIONAL DEEP DISH PIZZA DAY – Apr 5
NATIONAL GO FOR BROKE DAY – Apr 5
NATIONAL RAISIN AND SPICE BAR DAY – Apr 5
NATIONAL READ A ROAD MAP DAY – Apr 5

NATIONAL CARAMEL POPCORN DAY – Apr 6
NATIONAL SORRY CHARLIE DAY – Apr 6
NATIONAL STUDENT-ATHLETE DAY – Apr 6
National Tartan Day – Apr 6th
NATIONAL TEFLON DAY – Apr 6
NATIONAL WALKING DAY – First Wednesday in Apr
CHILDHELP NATIONAL DAY OF HOPE – Apr 2
NATIONAL BEER DAY – Apr 7
NATIONAL COFFEE CAKE DAY – Apr 7
No Housework Day – Apr 7th
NATIONAL ALCOHOL SCREENING DAY – Apr 10
NATIONAL ALL IS OURS DAY – Apr 8
NATIONAL EMPANADA DAY – Apr 8
NATIONAL ZOO LOVERS DAY – Apr 8
NATIONAL CHERISH AN ANTIQUE DAY – Apr 9
NATIONAL CHINESE ALMOND COOKIE DAY – Apr 9
NATIONAL FORMER PRISONER OF WAR RECOGNITION DAY – Apr 9
NATIONAL NAME YOURSELF DAY – Apr 9
NATIONAL WINSTON CHURCHILL DAY – Apr 9
NATIONAL CINNAMON CRESCENT DAY – Apr 10
NATIONAL ENCOURAGE A YOUNG WRITER DAY – Apr 10
NATIONAL FARM ANIMALS DAY – Apr 10
NATIONAL SIBLINGS DAY – Apr 10
NATIONAL BARBERSHOP QUARTET DAY – Apr 11
NATIONAL CHEESE FONDUE DAY – Apr 11
NATIONAL EIGHT TRACK TAPE DAY – Apr 11
NATIONAL PET DAY – Apr 11
NATIONAL SUBMARINE DAY – Apr 11
NATIONAL BIG WIND DAY – Apr 12
NATIONAL GRILLED CHEESE SANDWICH DAY – Apr 12
NATIONAL LICORICE DAY – Apr 12

NATIONAL LIBRARY WORKERS DAY – Apr 16

NATIONAL PEACH COBBLER DAY – Apr 13
NATIONAL SCRABBLE DAY – Apr 13
NATIONAL THOMAS JEFFERSON DAY – Apr 13
NATIONAL BOOKMOBILE DAY – Apr 16
NATIONAL DOLPHIN DAY – Apr 14
NATIONAL EX SPOUSE DAY – Apr 14
NATIONAL PAN AMERICAN DAY – Apr 14
NATIONAL PECAN DAY – Apr 14
NATIONAL REACH AS HIGH AS YOU CAN DAY – Apr 14
NATIONAL GLAZED SPIRAL HAM DAY – Apr 15
NATIONAL RUBBER ERASER DAY – Apr 15
NATIONAL TAKE A WILD GUESS DAY – Apr 15
NATIONAL TAX DAY – Apr 15
NATIONAL TITANIC REMEMBRANCE DAY – Apr 15
NATIONAL DAY OF SILENCE – Apr 19
NATIONAL EGGS BENEDICT DAY – Apr 16
NATIONAL HEALTHCARE DECISIONS DAY – Apr 16
NATIONAL WEAR YOUR PAJAMAS TO WORK DAY – Apr 16
-- National Auctioneers Day – Third Saturday in Apr
NATIONAL BAT APPRECIATION DAY – Apr 17
NATIONAL CHEESEBALL DAY – Apr 17
NATIONAL ELLIS ISLAND FAMILY HISTORY DAY – Apr 17
NATIONAL HAIKU POETRY DAY – Apr 17
NATIONAL ANIMAL CRACKERS DAY – Apr 18
NATIONAL COLUMNISTS DAY – Apr 18
NATIONAL LINEMAN APPRECIATION DAY – Apr 18
NATIONAL AMARETTO DAY – Apr 19
NATIONAL GARLIC DAY – Apr 19
NATIONAL HANGING OUT DAY – Apr 19
NATIONAL OKLAHOMA CITY BOMBING COMMEMORATION DAY – Apr 19
-- NATIONAL EDUCATION AND SHARING DAY – Changes Anually

NATIONAL LIMA BEAN RESPECT DAY – Apr 20
NATIONAL LOOK ALIKE DAY – Apr 20
NATIONAL PINEAPPLE UPSIDE DOWN CAKE DAY – Apr 20

NATIONAL CHOCOLATE COVERED CASHEWS DAY – Apr 21
NATIONAL KINDERGARTEN DAY – Apr 21
NATIONAL HIGH FIVE DAY – Third Thursday in Apr
NATIONAL EARTH DAY – Apr 22
NATIONAL GIRL SCOUT LEADERS DAY – Apr 22
NATIONAL JELLY BEAN DAY – Apr 22
NATIONAL CHERRY CHEESECAKE DAY – Apr 23
NATIONAL LOST DOG AWARENESS DAY – Apr 23
National Picnic Day – Apr 23
NATIONAL TAKE A CHANCE DAY – Apr 23
NATIONAL TALK LIKE SHAKESPEARE DAY – Apr 23
NATIONAL PIGS IN A BLANKET DAY – Apr 24
NATIONAL PET PARENTS DAY – Last Sunday in Apr
NATIONAL DNA DAY – Apr 25
NATIONAL EAST MEETS WEST DAY – Apr 25
NATIONAL HUG A PLUMBER DAY – Apr 25
NATIONAL TELEPHONE DAY – Apr 25
NATIONAL ZUCCHINI BREAD DAY – Apr 25
NATIONAL AUDUBON DAY – Apr 26
NATIONAL HELP A HORSE DAY – Apr 26
NATIONAL KIDS AND PETS DAY – Apr 26
NATIONAL PRETZEL DAY – Apr 26
NATIONAL RICHTER SCALE DAY – Apr 26

NATIONAL PRIME RIB DAY – Apr 27
NATIONAL TELL A STORY DAY – Apr 27
-- NATIONAL ADMINISTRATIVE PROFESSIONALS DAY – Wednesday of Last Full Week in Apr
NATIONAL BLUEBERRY PIE DAY – Apr 28
National BraveHearts Day – Apr 28th
NATIONAL GREAT POETRY READING DAY – Apr 28
WORKERS’ MEMORIAL DAY – Apr 28

-- NATIONAL TAKE OUR DAUGHTERS AND SONS TO WORK DAY – Fourth Thursday in Apr
NATIONAL PEACE ROSE DAY – Apr 29
NATIONAL SHRIMP SCAMPI DAY – Apr 29
NATIONAL ZIPPER DAY – Apr 29
NATIONAL ARBOR DAY – Last Friday in Apr
-- NATIONAL HAIRBALL AWARENESS DAY – Last Friday in Apr
NATIONAL TEACH CHILDREN TO SAVE DAY – Apr 11
NATIONAL ADOPT A SHELTER PET DAY – Apr 30
NATIONAL BUGS BUNNY DAY – Apr 30
NATIONAL HAIRSTYLISTS APPRECIATION DAY – Apr 30
NATIONAL HONESTY DAY – Apr 30
-- NATIONAL KISS OF HOPE DAY – Last Saturday of Apr
NATIONAL OATMEAL COOKIE DAY – Apr 30
NATIONAL RAISIN DAY – Apr 30
NATIONAL SARCOIDOSIS DAY – Apr 30
NATIONAL REBUILDING DAY – Apr 26
-- NATIONAL SENSE OF SMELL DAY – Last Saturday in Apr

-- May

LAW DAY – May 1
National Loyalty Day – May 1
NATIONAL CHOCOLATE PARFAIT DAY – May 1
NATIONAL MOTHER GOOSE DAY – May 1
SILVER STAR SERVICE BANNER DAY – May 1
-- NATIONAL INFERTILITY SURVIVAL DAY – Sunday before Mother’s Day
NATIONAL LEMONADE DAY – Aug 20
National Life Insurance Day – May 2
NATIONAL TRUFFLE DAY – May 2
NATIONAL MELANOMA MONDAY – First Monday in May
NATIONAL CHOCOLATE CUSTARD DAY – May 3
NATIONAL GARDEN MEDITATION DAY – May 3
NATIONAL LUMPY RUG DAY – May 3
NATIONAL PARANORMAL DAY – May 3
NATIONAL RASPBERRY POPOVER DAY – May 3
NATIONAL SPECIALLY-ABLED PETS DAY – May 3
NATIONAL TWO DIFFERENT COLORED SHOES DAY – May 3
NATIONAL TEACHER APPRECIATION DAY – May 7
BIRD DAY – May 4
NATIONAL CANDIED ORANGE PEEL DAY – May 4
NATIONAL ORANGE JUICE DAY – May 4
NATIONAL RENEWAL DAY – May 4
NATIONAL STAR WARS DAY – May 4
NATIONAL WEATHER OBSERVERS DAY – May 4
NATIONAL CARTOONISTS DAY – May 5

NATIONAL HOAGIE DAY – May 5
NATIONAL TOTALLY CHIPOTLE DAY – May 5
-- National Day of Prayer – First Thursday in May
-- NATIONAL DAY OF REASON – First Thursday in May
NATIONAL BEVERAGE DAY – May 6

NATIONAL NURSES DAY – May 6
-- NATIONAL SPACE DAY – First Friday in May
-- NATIONAL MILITARY SPOUSE APPRECIATION DAY – Friday before Mother’s Day
-- NATIONAL PROVIDER APPRECIATION DAY – Friday before Mother’s Day
NATIONAL BARRIER AWARENESS DAY – May 7

NATIONAL PASTE UP DAY – May 7
NATIONAL ROAST LEG OF LAMB DAY – May 7
JOIN HANDS DAY – May 3

-- NATIONAL HOMEBREW DAY – First Saturday in May
-- NATIONAL SCRAPBOOK DAY – First Saturday in May
National Start Seeing Monarchs Day – May 2
-- NATIONAL BABYSITTER’S DAY – Saturday before Mother’s Day
-- NATIONAL BIRTH MOTHER’S DAY – Saturday before Mother’s Day
NATIONAL TRAIN DAY – May 10

NATIONAL COCONUT CREAM PIE DAY – May 8
NATIONAL HAVE A COKE DAY – May 8

NATIONAL BUTTERSCOTCH BROWNIE DAY – May 9
NATIONAL LOST SOCK MEMORIAL DAY – May 9
NATIONAL MOSCATO DAY – May 9
-- NATIONAL WOMEN’S CHECKUP DAY – Second Monday in May
National Lipid Day – May 10
NATIONAL SHRIMP DAY – May 10
NATIONAL TWILIGHT ZONE DAY – May 11
NATIONAL SCHOOL NURSE DAY – May 8
-- NATIONAL RECEPTIONISTS DAY – Second Wednesday in May
-- NATIONAL THIRD SHIFT WORKERS DAY – Second Wednesday in May
NATIONAL FIBROMYALGIA AWARENESS DAY – May 12
NATIONAL LIMERICK DAY – May 12
NATIONAL NUTTY FUDGE DAY – May 12
NATIONAL ODOMETER DAY – May 12

NATIONAL APPLE PIE DAY – May 13
NATIONAL FROG JUMPING DAY – May 13
NATIONAL FRUIT COCKTAIL DAY – May 13
-- NATIONAL BLAME SOMEONE ELSE DAY – First Friday the Thirteenth of the Year
National Archery Day – Changes Annually
NATIONAL BUTTERMILK BISCUIT DAY – May 14
NATIONAL DANCE LIKE A CHICKEN DAY – May 14
NATIONAL UNDERGROUND AMERICA DAY – May 14
-- CORNELIA DE LANGE SYNDROME AWARENESS DAY – Second Saturday in May
-- NATIONAL MINIATURE GOLF DAY – Second Saturday in May
-- STAMP OUT HUNGER FOOD DRIVE DAY – Second Saturday in May
NATIONAL CHOCOLATE CHIP DAY – May 15
NATIONAL NYLON STOCKING DAY – May 15
Peace Officers Memorial Day
NATIONAL BIOGRAPHER’S DAY – May 16
NATIONAL COQUILLES SAINT JACQUES DAY – May 16
NATIONAL LOVE A TREE DAY – May 16
NATIONAL PIERCING DAY – May 16
NATIONAL SEA MONKEY DAY – May 16

NATIONAL CHERRY COBBLER DAY – May 17
NATIONAL PACK RAT DAY – May 17

NATIONAL CHEESE SOUFFLE DAY – May 18
-- EMERGENCY MEDICAL SERVICES FOR CHILDREN DAY – Wednesday of EMS Week
NATIONAL HIV VACCINE AWARENESS DAY – May 18
NATIONAL NO DIRTY DISHES DAY – May 18
NATIONAL VISIT YOUR RELATIVES DAY – May 18
NATIONAL DEVIL’S FOOD CAKE DAY – May 19
NATIONAL MAY RAY DAY – May 19
NATIONAL BE A MILLIONAIRE DAY – May 19
NATIONAL PICK STRAWBERRIES DAY – May 19
NATIONAL QUICHE LORRAINE DAY – May 20
-- NATIONAL BIKE TO WORK DAY – Third Friday in May
-- NATIONAL DEFENSE TRANSPORTATION DAY- Third Friday in May
-- NATIONAL ENDANGERED SPECIES DAY – Third Friday in May
-- NATIONAL PIZZA PARTY DAY! – Third Friday in May
NASCAR DAY – Third Friday in May
NATIONAL AMERICAN RED CROSS FOUNDER’S DAY – May 21
NATIONAL MEMO DAY – May 21
NATIONAL STRAWBERRIES AND CREAM DAY – May 21
NATIONAL WAITSTAFF DAY – May 21
NATIONAL ARMED FORCES DAY – Third Saturday in May
NATIONAL LEARN TO SWIM DAY – Third Saturday in May
NATIONAL BUY A MUSICAL INSTRUMENT DAY – May 22
NATIONAL MARITIME DAY – May 22
NATIONAL VANILLA PUDDING DAY – May 22
NATIONAL LUCKY PENNY DAY – May 23
NATIONAL TAFFY DAY – May 23
NATIONAL ESCARGOT DAY – May 24
NATIONAL SCAVENGER HUNT DAY – May 24

NATIONAL BROWN-BAG-IT DAY – May 25
NATIONAL MISSING CHILDREN’S DAY – May 25
NATIONAL TAP DANCE DAY – May 25
NATIONAL WINE DAY – May 25
-- NATIONAL SENIOR HEALTH & FITNESS DAY – Last Wednesday in May

NATIONAL BLUEBERRY CHEESECAKE DAY – May 26

NATIONAL CELLOPHANE TAPE DAY – May 27
NATIONAL GRAPE POPSICLE DAY – May 27
NATIONAL DON’T FRY DAY – Friday before Memorial Day
-- NATIONAL HEAT AWARENESS DAY – Last Friday in May
NATIONAL BRISKET DAY – May 28
NATIONAL HAMBURGER DAY – May 28
NATIONAL COQ AU VIN DAY – May 29
NATIONAL PAPERCLIP DAY – May 29
LOOMIS DAY – May 30
NATIONAL HOLE IN MY BUCKET DAY – May 30
NATIONAL MINT JULEP DAY – May 30
NATIONAL WATER A FLOWER DAY – May 30
MEMORIAL DAY – Last Monday in May
NATIONAL MACAROON DAY – May 31
NATIONAL SAVE YOUR HEARING DAY – May 31
NATIONAL SPEAK IN COMPLETE SENTENCES DAY – May 31


-- Jun

NATIONAL GO BAREFOOT DAY – Jun 1
NATIONAL HAZELNUT CAKE DAY – Jun 1
NATIONAL HEIMLICH MANEUVER DAY – Jun 1
NATIONAL PENPAL DAY – Jun 1
NATIONAL SAY SOMETHING NICE DAY – Jun 1
NATIONAL RUNNING DAY – First Wednesday in Jun
National Rotisserie Chicken Day – Jun 2
NATIONAL BUBBA DAY – Jun 2
NATIONAL ROCKY ROAD DAY – Jun 2
NATIONAL LEAVE THE OFFICE EARLY DAY – Jun 2
NATIONAL CHOCOLATE MACAROON DAY – Jun 3
NATIONAL REPEAT DAY – Jun 3

NATIONAL DOUGHNUT DAY – First Friday in Jun
NATIONAL CHEESE DAY – Jun 4th
NATIONAL COGNAC DAY – Jun 4
NATIONAL OLD MAIDS DAY – Jun 4
NATIONAL TRAILS DAY – First Saturday in Jun
NATIONAL GINGERBREAD DAY – Jun 5
-- NATIONAL CANCER SURVIVORS DAY – First Sunday in Jun
National Higher Education Day – Jun 6
NATIONAL APPLESAUCE CAKE DAY – Jun 6
NATIONAL DRIVE-IN MOVIE DAY – Jun 6
NATIONAL GARDENING EXERCISE DAY – Jun 6
NATIONAL YO-YO DAY – Jun 6
NATIONAL CHOCOLATE ICE CREAM DAY – Jun 7
NATIONAL VCR DAY – Jun 7
National Best Friends Day
NATIONAL NAME YOUR POISON DAY – Jun 8
NATIONAL UPSY DAISY DAY – Jun 8

NATIONAL DONALD DUCK DAY – Jun 9
NATIONAL STRAWBERRY RHUBARB PIE DAY – Jun 9

National Ballpoint Pen Day – Jun 10
NATIONAL BLACK COW DAY – Jun 10
NATIONAL HERBS AND SPICES DAY – Jun 10
NATIONAL ICED TEA DAY – Jun 10
National Making Life Beautiful Day – Jun 11
National Rosé Day – Second Saturday in Jun
NATIONAL CORN ON THE COB DAY – Jun 11
NATIONAL GERMAN CHOCOLATE CAKE DAY – Jun 11
NATIONAL JERKY DAY – Jun 12
NATIONAL LOVING DAY – Jun 12
NATIONAL PEANUT BUTTER COOKIE DAY – Jun 12
NATIONAL RED ROSE DAY – Jun 12

NATIONAL KITCHEN KLUTZES OF AMERICA DAY – Jun 13
NATIONAL SEWING MACHINE DAY – Jun 13
NATIONAL WEED YOUR GARDEN DAY – Jun 13
NATIONAL BOURBON DAY – Jun 14
NATIONAL FLAG DAY – Jun 14

NATIONAL POP GOES THE WEASEL DAY 0 Jun 14
NATIONAL STRAWBERRY SHORTCAKE DAY – Jun 14
NATIONAL SMILE POWER DAY – Jun 15
NATURE PHOTOGRAPHY DAY – Jun 15
NATIONAL FUDGE DAY – Jun 16
-- NATIONAL DUMP THE PUMP DAY – Third Thursday in Jun
NATIONAL APPLE STRUDEL DAY – Jun 17
NATIONAL EAT YOUR VEGETABLES DAY – Jun 17
NATIONAL STEWART’S ROOT BEER DAY – Jun 17
NATIONAL CHERRY TART DAY – Jun 17
NATIONAL FLIP FLOP DAY – Third Friday in Jun
NATIONAL GO FISHING DAY – Jun 18
NATIONAL SPLURGE DAY – Jun 18

NATIONAL MARTINI DAY – Jun 19
NATIONAL AMERICAN EAGLE DAY – Jun 20
NATIONAL ICE CREAM SODA DAY – Jun 19
NATIONAL VANILLA MILKSHAKE DAY - Jun 20
NATIONAL DAYLIGHT APPRECIATION DAY – Jun 21
NATIONAL PEACHES ‘N’ CREAM DAY – Jun 21

NATIONAL CHOCOLATE ECLAIR DAY – Jun 22
NATIONAL ONION RINGS DAY – Jun 22

NATIONAL PECAN SANDIES DAY – Jun 23
NATIONAL PINK DAY – Jun 23
NATIONAL PRALINES DAY – Jun 24

NATIONAL CATFISH DAY – Jun 25
NATIONAL LEON DAY – Jun 25
NATIONAL STRAWBERRY PARFAIT DAY – Jun 25
NATIONAL BEAUTICIAN’S DAY – Jun 26
NATIONAL CHOCOLATE PUDDING DAY – Jun 26
NATIONAL ORANGE BLOSSOM DAY – Jun 27

NATIONAL SUNGLASSES DAY – Jun 27
NATIONAL PAUL BUNYAN DAY – Jun 28
NATIONAL INSURANCE AWARENESS DAY – Jun 28

NATIONAL ALMOND BUTTERCRUNCH DAY – Jun 29
NATIONAL CAMERA DAY – Jun 29
NATIONAL WAFFLE IRON DAY – Jun 29
NATIONAL METEOR WATCH DAY – Jun 30

NATIONAL BOMB POP DAY – Last Thursday in Jun
NATIONAL HANDSHAKE DAY – Last Thursday in Jun

-- Jul

NATIONAL POSTAL WORKER DAY – Jul 1
NATIONAL U.S. POSTAGE STAMP DAY – Jul 1
NATIONAL CREATIVE ICE CREAM FLAVORS DAY – Jul 1
NATIONAL GINGERSNAP DAY – Jul 1
NATIONAL ANISETTE DAY – Jul 2
HOP-A-PARK DAY – Jul 5

NATIONAL EAT YOUR BEANS DAY – Jul 3
NATIONAL CHOCOLATE WAFER DAY – Jul 3
Independence Day – Jul 4
NATIONAL BARBECUED SPARERIBS DAY – Jul 4
NATIONAL CAESAR SALAD DAY – Jul 4
NATIONAL APPLE TURNOVER DAY – Jul 5
National Graham Cracker Day – Jul 5

NATIONAL FRIED CHICKEN DAY – Jul 6
NATIONAL FATHER DAUGHTER TAKE A WALK DAY – Jul 7
NATIONAL STRAWBERRY SUNDAE DAY – Jul 7
NATIONAL MACARONI DAY – Jul 7
NATIONAL CHOCOLATE WITH ALMONDS DAY – Jul 7
COLLECTOR CAR APPRECIATION DAY – Jul 11
NATIONAL SUGAR COOKIE DAY – Jul 9
NATIONAL CLERIHEW DAY – Jul 10
NATIONAL PINA COLADA DAY – Jul 10
NATIONAL CHEER UP THE LONELY DAY – Jul 11
NATIONAL RAINIER CHERRY DAY – Jul 11
NATIONAL BLUEBERRY MUFFIN DAY – Jul 11
ALL AMERICAN PET PHOTO DAY – Jul 11
NATIONAL MOJITO DAY – Jul 11

NATIONAL SIMPLICITY DAY – Jul 12
NATIONAL DIFFERENT COLORED EYES DAY – Jul 12
NATIONAL PECAN PIE DAY – Jul 12
PAPER BAG DAY – Jul 12

NATIONAL FRENCH FRY DAY – Jul 13
NATIONAL BEANS ‘N’ FRANKS DAY – Jul 13
NATIONAL GRAND MARNIER DAY – Jul 14
NATIONAL TAPE MEASURE DAY – Jul 14
NATIONAL NUDE DAY – Jul 14
I LOVE HORSES DAY – Jul 15
NATIONAL TAPIOCA PUDDING DAY – Jul 15

-- NATIONAL STRAWBERRY RHUBARB WINE DAY – Third Saturday in Jul
NATIONAL CORN FRITTERS DAY – Jul 16
NATIONAL PERSONAL CHEF DAY – Jul 16
-- TOSS AWAY THE “COULD HAVES” AND “SHOULD HAVES” DAY – Third Saturday in Jul

NATIONAL PEACH ICE CREAM DAY – Jul 17
NATIONAL WRONG WAY CORRIGAN DAY – Jul 17
NATIONAL YELLOW PIG DAY – Jul 17
-- NATIONAL ICE CREAM DAY – Third Sunday in Jul

NATIONAL CAVIAR DAY – Jul 18
-- National Get Out of the Dog House Day – Third Monday in Jul
NATIONAL DAIQUIRI DAY – Jul 19

NATIONAL LOLLIPOP DAY – Jul 20
NATIONAL JUNK FOOD DAY – Jul 21

National Penuche Fudge Day – Jul 22
NATIONAL HAMMOCK DAY – Jul 22
NATIONAL RAT CATCHER’S DAY – Jul 22

THERMAL ENGINEERING DAY – Jul 24
NATIONAL TEQUILA DAY – Jul 24
NATIONAL DRIVE-THRU DAY – Jul 24
NATIONAL COUSINS DAY – Jul 24
-- NATIONAL PARENTS DAY – Fourth Sunday in Jul
NATIONAL MERRY-GO-ROUND DAY – Jul 25
NATIONAL HOT FUDGE SUNDAE DAY – Jul 25
NATIONAL CULINARIANS DAY – Jul 25
NATIONAL THREAD THE NEEDLE DAY – Jul 25

NATIONAL BAGELFEST DAY – Jul 26

NATIONAL SCOTCH DAY – Jul 27
NATIONAL CREME BRULEE DAY – Jul 21
NATIONAL MILK CHOCOLATE DAY – Jul 28
BUFFALO SOLDIERS DAY – Jul 28

-- NATIONAL CHILI DOG DAY – Last Thursday in Jul
NATIONAL LASAGNA DAY – Jul 29

NATIONAL CHICKEN WING DAY – Jul 29
-- NATIONAL TALK IN AN ELEVATOR DAY – Last Friday in Jul
-- NATIONAL SYSTEM ADMINISTRATOR APPRECIATION DAY – Last Friday in Jul
NATIONAL CHEESECAKE DAY – Jul 30
NATIONAL FATHER-IN-LAW-DAY – Jul 30
NATIONAL DANCE DAY – Last Saturday in Jul
NATIONAL RASPBERRY CAKE DAY – Jul 31
NATIONAL MUTT DAY – Jul 31

-- Aug

NATIONAL RASPBERRY CREAM PIE DAY – Aug 1
NATIONAL GIRLFRIENDS DAY – Aug 1
NATIONAL MINORITY DONOR AWARENESS DAY – Aug 1
RESPECT FOR PARENTS DAY – Aug 1

NATIONAL ICE CREAM SANDWICH DAY – Aug 2
NATIONAL NIGHT OUT DAY – First Tuesday in Aug
NATIONAL WATERMELON DAY – Aug 3
NATIONAL GRAB SOME NUTS DAY – Aug 3
NATIONAL CHOCOLATE CHIP DAY – Aug 4
NATIONAL COAST GUARD DAY – Aug 4
National Underwear Day – Aug 5
NATIONAL OYSTER DAY – Aug 5

NATIONAL ROOT BEER FLOAT DAY – Aug 6
NATIONAL FRESH BREATH DAY – Aug 6
NATIONAL WIGGLE YOUR TOES DAY – Aug 6
NATIONAL MUSTARD DAY – First Saturday in Aug
MEAD DAY – First Saturday in Aug
PURPLE HEART DAY – Aug 7
NATIONAL LIGHTHOUSE DAY – Aug 7
NATIONAL RASPBERRIES N’ CREAM DAY – Aug 7
-- NATIONAL KIDS DAY – First Sunday in Aug
-- AMERICAN FAMILY DAY – First Sunday in Aug
-- NATIONAL FRIENDSHIP DAY – First Sunday in Aug
National Sisters Day - Aug 3
NATIONAL HAPPINESS HAPPENS DAY – Aug 8
National Frozen Custard Day – Aug 8
NATIONAL SNEAK SOME ZUCCHINI INTO YOUR NEIGHBOR’S PORCH DAY – Aug 8
NATIONAL DOLLAR DAY – Aug 8
NATIONAL RICE PUDDING DAY – Aug 9
NATIONAL VEEP DAY – Aug 9
NATIONAL BOOK LOVERS DAY – Aug 9
NATIONAL LAZY DAY – Aug 10
NATIONAL S’MORES DAY – Aug 10

NATIONAL PRESIDENTIAL JOKE DAY – Aug 11
NATIONAL RASPBERRY BOMBE DAY – Aug 11
NATIONAL JULIENNE FRIES DAY – Aug 12
NATIONAL VINYL RECORD DAY – Aug 12
NATIONAL MIDDLE CHILD DAY – Aug 12
NATIONAL FILET MIGNON DAY – Aug 13

NATIONAL BOWLING DAY – 2nd Saturday in Aug
-- NATIONAL GARAGE SALE DAY – 2nd Saturday in Aug
NATIONAL V-J DAY – Aug 14
NATIONAL CREAMSICLE DAY – Aug 14
NATIONAL V-J DAY – Aug 15
NATIONAL RELAXATION DAY – Aug 15
NATIONAL LEMON MERINGUE PIE DAY – Aug 15
NATIONAL TELL A JOKE DAY – Aug 16
NATIONAL ROLLER COASTER DAY – Aug 16
NATIONAL AIRBORNE DAY – Aug 16
NATIONAL RUM DAY – Aug 16

NATIONAL THRIFT SHOP DAY – Aug 17
NATIONAL MAIL ORDER CATALOG DAY – Aug 18
NATIONAL ICE CREAM PIE DAY – Aug 18
NATIONAL AVIATION DAY – Aug 19
NATIONAL SOFT ICE CREAM DAY – Aug 19
NATIONAL RADIO DAY – Aug 20
NATIONAL CHOCOLATE PECAN PIE DAY – Aug 20
BRAZILIAN BLOWOUT DAY – Aug 21
NATIONAL SPUMONI DAY – Aug 21
NATIONAL SENIOR CITIZENS DAY – Aug 21
NATIONAL TOOTH FAIRY DAY – Aug 22
NATIONAL PECAN TORTE DAY – Aug 22
NATIONAL RIDE THE WIND DAY – Aug 23
NATIONAL SPONGE CAKE DAY – Aug 23
NATIONAL PEACH PIE DAY – Aug 24
NATIONAL WAFFLE DAY – Aug 24
NATIONAL WHISKEY SOUR DAY – Aug 25
NATIONAL KISS AND MAKE UP DAY – Aug 25
NATIONAL SECONDHAND WARDROBE DAY – Aug 25
NATIONAL BANANA SPLIT DAY – Aug 25

NATIONAL DOG DAY – Aug 26
NATIONAL WOMEN’S EQUALITY DAY – Aug 26
NATIONAL CHERRY POPSICLE DAY – Aug 26
NATIONAL POTS DE CREME DAY – Aug 27
NATIONAL JUST BECAUSE DAY – Aug 27
NATIONAL CHERRY TURNOVERS DAY – Aug 28
NATIONAL CHOP SUEY DAY – Aug 29
NATIONAL TRAIL MIX DAY – Aug 31

-- Sep

NATIONAL CHICKEN BOY’S DAY – Sep 1
NATIONAL NO RHYME (NOR REASON) DAY – Sep 1
NATIONAL BLUEBERRY POPSICLE DAY – Sep 2
2
-- NATIONAL COLLEGE COLORS DAY – First Friday of College School Year

NATIONAL WELSH RAREBIT DAY – Sep 3
U.S. BOWLING LEAGUE DAY
NATIONAL WILDLIFE DAY – Sep 4
NATIONAL NEWSPAPER CARRIER DAY – Sep 4
NATIONAL MACADAMIA NUT DAY – Sep 4
NATIONAL HUG YOUR BOSS DAY – Aug 23
NATIONAL CHEESE PIZZA DAY – Sep 5
NATIONAL LABOR DAY – First Monday in Sep
NATIONAL COFFEE ICE CREAM DAY – Sep 6
NATIONAL READ A BOOK DAY – Sep 6
-- NATIONAL ANOTHER LOOK UNLIMITED DAY – Day After Labor Day

NATIONAL NEITHER RAIN NOR SNOW DAY – Sep 7
NATIONAL GRANDMA MOSES DAY – Sep 7
NATIONAL ACORN SQUASH DAY – Sep 7
NATIONAL SALAMI DAY – Sep 7
NATIONAL PEDIATRIC HEMATOLOGY/ONCOLOGY NURSES DAY – Sep 8

NATIONAL TEDDY BEAR DAY – Sep 9
-- Stand Up To Cancer Day – Second Saturday in Sep
NATIONAL SWAP IDEAS DAY – Sep 10
NATIONAL TV DINNER DAY – Sep 10
NATIONAL MAKE YOUR BED DAY – Sep 11
NATIONAL HOT CROSS BUN DAY – Sep 11
PATRIOT DAY AND NATIONAL DAY OF SERVICE AND REMBERANCE – Sep 11
-- NATIONAL PET MEMORIAL DAY – Second Sunday in Sep
NATIONAL HUG YOUR HOUND DAY – Sep 8
-- NATIONAL GRANDPARENTS DAY – Sunday After Labor Day
NATIONAL VIDEO GAMES DAY – Sep 12
NATIONAL CHOCOLATE MILKSHAKE DAY – Sep 12

National Programmers Day – 265th Day of the Year
-- NATIONAL BOSS/EMPLOYEE EXCHANGE DAY – Monday After Labor Day
NATIONAL KIDS TAKE OVER THE KITCHEN DAY – Sep 13
NATIONAL PEANUT DAY – Sep 13
-- National Ants on a Log Day – Second Tuesday in Sep
National Cream Filled Donut Day – Sep 14
National Linguine Day – Sep 15
National Felt Hat Day – Sep 15
National Double Cheeseburger Day – Sep 15
National LGBT Center Awareness Day – Sep 15
National Creme de Menthe Day – Sep 15
Google.com Day – Sep 15
Greenpeace Day – Sep 15
National Play-Doh Day – Sep 16th
National Cinnamon Raisin Bread Day – Sep 16
National Step Family Day – Sep 16

Anne Bradstreet Day – Sep 16
2Mayflower Day – Sep 16
Trail of Tears Commemoration Day – Sep 16
-- NATIONAL TRADESMEN DAY – Third Friday in Sep
-- National POW/MIA Recognition Day – Third Friday in Sep
NATIONAL APPLE DUMPLING DAY – Sep 17
CONSTITUTION DAY AND CITIZENSHIP DAY – Sep 17
-- Big Whopper Liar Day – Third Saturday in Sep
-- Boys’ and Girls’ Club Day for Kids – Third Saturday in Sep
-- Puppy Mill Awareness Day – Third Saturday in Sep
-- Responsible Dog Ownership Day – Third Saturday in Sep

NATIONAL CHEESEBURGER DAY – Sep 18
NATIONAL HIV/AIDS AND AGING AWARENESS DAY – Sep 17
-- Wife Appreciation Day – Third Sunday in Sep
SEPTEMBER 19, 2013 – NATIONAL BUTTERSCOTCH PUDDING DAY
International Talk Like a Pirate Day – Sep 19
National Punch Day – Sep 20
-- National IT Professionals Day – Third Tuesday in Sep
NATIONAL PECAN COOKIE DAY – Sep 21
National Centenarian’s Day – Sep 22
National White Chocolate Day – Sep 22
AKC Responsible Dog Ownership Day – Sep 22
American Business Women’s Day – Sep 22
Car Free Day – Sep 22
Dear Diary Day – Sep 22
Elephant Appreciation Day – Sep 22
Hobbit Day – Sep 22
Autumnal Equinox – Sep 22
NATIONAL CHECKERS DAY AND DOGS IN POLITICS DAY – Sep 23
NATIONAL GREAT AMERICAN POT PIE DAY – Sep 23
Celebrate Bi-sexuality Day – Sep 23
Restless Legs Awareness Day – Sep 23
Innergize Day – Sep 23
National Cherries Jubilee Day – Sep 24

Schwenkfelder Thanksgiving – Sep 24
National Hunting and Fishing Day – Sep 27
-- NATIONAL FAMILY HEALTH & FITNESS DAY USA – Last Saturday in Sep
-- NATIONAL PUBLIC LANDS DAY – Last Saturday in Sep
NATIONAL ONE-HIT WONDER DAY – Sep 25
NATIONAL COMIC BOOK DAY – Sep 25
NATIONAL TUNE-UP DAY – Sep 25

Math Story Telling Day – Sep 25
-- GOLD STAR MOTHER’S DAY – Last Sunday in Sep

National Dumpling Day – Sep 26
NATIONAL JOHNNY APPLESEED DAY – Sep 26
NATIONAL SHAMU THE WHALE DAY – Sep 26
NATIONAL PANCAKE DAY – Sep 26
NATIONAL CHOCOLATE MILK DAY – Sep 27
NATIONAL CRUSH A CAN DAY – Sep 27
NATIONAL CORNED BEEF HASH DAY – Sep 27
-- National Woman Road Warrior Day – Fourth Tuesday in Sep
NATIONAL VOTER REGISTRATION DAY – Sep 24
National Good Neighbor Day – Sep 28
NATIONAL STRAWBERRY CREAM PIE DAY – Sep 28
-- NATIONAL WOMEN’S HEALTH & FITNESS DAY – Last Wednesday in Sep
National Coffee Day – Sep 29
VFW Day – Sep 29
NATIONAL CHEWING GUM DAY – Sep 30
NATIONAL MUD PACK DAY – Sep 30
National Hot Mulled Cider Day – Sep 30

-- Oct

National Fire Pup Day – Oct 1
National Homemade Cookies Day – Oct 1
National Custodial Workers Recognition Day – Oct 2
NATIONAL NAME YOUR CAR DAY – Oct 2
NATIONAL FRIED SCALLOPS DAY – Oct 2
NATIONAL TECHIES DAY – Oct 3
-- NATIONAL CHILD HEALTH DAY – First Monday in Oct
NATIONAL TACO DAY – Oct 4
NATIONAL GOLF LOVERS DAY – Oct 4
NATIONAL VODKA DAY – Oct 4
NATIONAL DO SOMETHING NICE DAY – Oct 5
NATIONAL APPLE BETTY DAY – Oct 5

NATIONAL MAD HATTER DAY – Oct 6
NATIONAL GERMAN-AMERICAN DAY – Oct 6
NATIONAL NOODLE DAY – Oct 6
2
NATIONAL FRAPPE DAY – Oct 7

NATIONAL FLUFFERNUTTER DAY – Oct 8
NATIONAL PIEROGI DAY – Oct 8
American Touch Tag Day – Oct 8
-- National Costume Swap Day – Second Sunday in Oct
National Costume Swap Day – Oct 12

NATIONAL LEIF ERIKSON DAY – Oct 9
NATIONAL PRO-LIFE CUPCAKE DAY – Oct 9
NATIONAL MOLDY CHEESE DAY – Oct 9
National Chess Day – Oct 13
-- Clergy Appreciation Day – Second Sunday in Oct
NATIONAL ANGEL FOOD CAKE DAY – Oct 10
-- National Kick Butt Day – Second Monday in Oct
-- Native American Day – Second Monday in Oct
-- Columbus Day – Second Monday in Oct
NATIONAL SAUSAGE PIZZA DAY – Oct 11
NATIONAL COMING OUT DAY – Oct 11
GENERAL PULASKI MEMORIAL DAY – Oct 11
NATIONAL FREETHOUGHT DAY – Oct 12
NATIONAL FARMERS DAY – Oct 12
NATIONAL GUMBO DAY – Oct 12
-- National Fossil Day – Wednesday of Second Full Week in Oct
-- NATIONAL EMERGENCY NURSES DAY – Second Wednesday in Oct
-- NATIONAL BRING YOUR TEDDY BEAR TO WORK AND SCHOOL DAY – Second Wednesday in Oct
-- NATIONAL STOP BULLYING DAY – Second Wednesday in Oct
NATIONAL TRAIN YOUR BRAIN DAY – Oct 13
NATIONAL YORKSHIRE PUDDING DAY – Oct 13
Navy Birthday – Oct 13

NATIONAL DESSERT DAY – Oct 14
Be Bald and Be Free Day – Oct 14
NATIONAL TAKE YOUR PARENTS TO LUNCH DAY – Oct 16

NATIONAL i LOVE LUCY DAY – Oct 15
National Cake Decorating Day – Oct 15
National Grouch Day – Oct 15
NATIONAL LATINO AIDS AWARENESS DAY – Oct 15
NATIONAL PREGNANCY AND INFANT LOSS REMEMBRANCE DAY – Oct 15
White Cane Safety Day – Oct 15
-- NATIONAL SWEETEST DAY – Third Saturday in Oct
NATIONAL LIQUEUR DAY – Oct 16
NATIONAL DICTIONARY DAY – Oct 16
National Feral Cat Day – Oct 16
Department Store Day – Oct 16
National Edge Day – Oct 17
NATIONAL MULLIGAN DAY – Oct – 17
National Pasta Day – Oct 17
Alternative Fuel Day – Oct 17
Black Poetry Day – Oct 17
NATIONAL BOSS’S DAY – Oct 16
-- NATIONAL CLEAN YOUR VIRTUAL DESKTOP DAY – Third Monday in Oct
National Chocolate Cupcake Day – Oct 18

Pro-Life Day of Silent Solidarity – Oct 16

NATIONAL SEAFOOD BISQUE DAY – Oct 19
Hagfish Day – Third Wednesday in Oct
-- Support Your Local Chamber of Commerce – Third Wednesday in Oct
-- Medical Assistants Recognition Day – Wednesday of Third Full Week in Oct
NATIONAL BRANDIED FRUIT DAY – Oct 20
-- NATIONAL GET SMART ABOUT CREDIT DAY – Third Thursday in Oct
Get to Know Your Customers Day – Oct 17
NATIONAL PUMPKIN CHEESECAKE DAY – Oct 21
NATIONAL REPTILE AWARENESS DAY – Oct 21
-- National Mammography Day – Third Friday in Oct
National Mammography Day – Oct 17
NATIONAL NUT DAY – Oct 22
NATIONAL COLOR DAY – Oct 22
-- NATIONAL MAKE A DIFFERENCE DAY – Fourth Saturday in Oct
NATIONAL BOSTON CREAM PIE DAY – Oct 23
National Mole Day – Oct 23
NATIONAL TV TALK SHOW HOST DAY – Oct 23
Swallows Depart from San Juan Capistrano Day – Oct 23
IPOD Day Oct 23
-- NATIONAL MOTHER-IN-LAW DAY – Fourth Sunday in Oct
NATIONAL FOOD DAY – Oct 24
NATIONAL BOLOGNA DAY – Oct 24
United Nations Day – Oct 24
NATIONAL GREASY FOODS DAY – Oct 25
Sourest Day – Oct 25
Chucky, the Notorious Killer Doll Day – Oct 25
NATIONAL DAY OF THE DEPLOYED – Oct 26
NATIONAL MULE DAY – Oct 26
NATIONAL PUMPKIN DAY – Oct 26
NATIONAL MINCEMEAT DAY – Oct 26
NATIONAL AMERICAN BEER DAY – Oct 27
Navy Day – Oct 27
NATIONAL CHOCOLATE DAY – Oct 28
-- National Pharmacy Buying Day – Friday of Third Full Week in Oct
National Pharmacy Buying Day – Oct 24
-- NATIONAL FRANKENSTEIN FRIDAY – Last Friday in Oct
-- National Breadstix (Bread Sticks) Day – Last Friday in Oct or Oct 31
NATIONAL CAT DAY – Oct 29
NATIONAL OATMEAL DAY – Oct 29
NATIONAL HERMIT DAY – Oct 29
Speak Up For Service Day – Oct 30

NATIONAL CANDY CORN DAY – Oct 30
NATIONAL CARAMEL APPLE DAY – Oct 31
NATIONAL KNOCK KNOCK JOKE DAY – Oct 31
NATIONAL MAGIC DAY – Oct 31
GIRL SCOUT FOUNDERS DAY – Oct 31
Halloween – Oct 31

-- Nov

National Authors Day – Nov 1
NATIONAL FAMILY LITERACY DAY – Nov 1
NATIONAL COOK FOR YOUR PETS DAY – Nov 1
NATIONAL VINEGAR DAY – Nov 1
NATIONAL DEEP FRIED CLAMS DAY – Nov 1

NATIONAL DEVILED EGG DAY – Nov 2
NATIONAL TRAFFIC DIRECTORS DAY – Nov 4
NATIONAL HOUSEWIFE’S DAY – Nov 3

-- NATIONAL MEN MAKE DINNER DAY – First Thursday in Nov
NATIONAL CHICKEN LADY DAY – Nov 4
National Candy Day – Nov 4

NATIONAL DOUGHNUT DAY – Nov 5

NATIONAL NACHOS DAY – Nov 6
NATIONAL SAXOPHONE DAY – Nov 6
Daylight Saving Time Ends – Nov 2
National Bittersweet Chocolate with Almonds Day – Nov 7

NATIONAL CAPPUCCINO DAY – Nov 8
NATIONAL HARVEY WALLBANGER DAY – Nov 8
NATIONAL PARENTS AS TEACHERS DAY – Nov 8

NATIONAL SCRAPPLE DAY – Nov 9
United States Marine Corps. Birthday – Nov 10
NATIONAL FORGET-ME-NOT DAY – Nov 10
NATIONAL VANILLA CUPCAKE DAY – Nov 10
NATIONAL SUNDAE DAY – Nov 11
Veterans Day – Nov 11
NATIONAL PIZZA WITH THE WORKS EXCEPT ANCHOVIES DAY – Nov 12
NATIONAL CHICKEN SOUP FOR THE SOUL DAY – Nov 12
NATIONAL INDIAN PUDDING DAY – Nov 13
NATIONAL PICKLE DAY – Nov 14
NATIONAL SPICY GUACAMOLE DAY – Nov 14
NATIONAL BUNDT DAY – Nov 15
NATIONAL PHILANTHROPY DAY – Nov 15
NATIONAL CLEAN OUT YOUR REFRIGERATOR DAY – Nov 15
National Spicy Hermit Cookie Day – Nov 15
NATIONAL RAISIN BRAN CEREAL DAY – Nov 15
AMERICA RECYCLES DAY – Nov 15
-- National Fast Food Day
-- National Button Day
-- NATIONAL EDUCATION SUPPORT PROFESSIONALS DAY – Wednesday of American Education Week
NATIONAL BAKLAVA DAY – Nov 17
NATIONAL TAKE A HIKE DAY – Nov 17
-- GREAT AMERICAN SMOKEOUT DAY – Thursday Before Thanksgiving
NATIONAL VICHYSSOISE DAY – Nov 18
Mickey Mouse Birthday – Nov 18
NATIONAL CARBONATED BEVERAGE WITH CAFFEINE DAY – Nov 19
NATIONAL PLAY MONOPOLY DAY – Nov 19
-- NATIONAL ADOPTION DAY – Saturday Before Thanksgiving
NATIONAL PEANUT BUTTER FUDGE DAY – Nov 20
NATIONAL ABSURDITY DAY – Nov 20
NATIONAL STUFFING DAY – Nov 21
NATIONAL CRANBERRY RELISH DAY – Nov 22
NATIONAL CASHEW DAY – Nov 23
NATIONAL EAT A CRANBERRY DAY – Nov 23
NATIONAL ESPRESSO DAY – Nov 23
NATIONAL TIE ONE ON DAY – Day Before Thanksgiving
NATIONAL SARDINES DAY – Nov 24
-- National Day of Mourning – Fourth Thursday in Nov
-- THANKSGIVING DAY – Fourth Thursday in Nov
Turkey Free Thanksgiving – Nov 28
National Parfait Day – Nov 25
-- Blase’ Day
-- Shopping Reminder Day
-- NATIONAL DAY OF LISTENING – Day After Thanksgiving
-- NATIONAL NATIVE AMERICAN HERITAGE DAY – Day After Thanksgiving
-- Black Friday – Day After Thanksgiving
-- Buy Nothing Day – First Shopping Day After Thanksgiving
-- NATIONAL FLOSSING DAY – Day After Thanksgiving
-- Maize Day – Day After Thanksgiving
-- Your Welcomegiving Day – Day After Thanksgiving
NATIONAL CAKE DAY – Nov 26
-- Small Business Saturday – Saturday following Thanksgiving
NATIONAL BAVARIAN CREAM PIE DAY – Nov 27
NATIONAL FRENCH TOAST DAY – Nov 28
-- Cyber Monday – Monday After Thanksgiving
Electronic Greeting Day – Nov 29
-- National Day of Giving – #GivingTuesday – usually follows Cyber Monday
NATIONAL MOUSSE DAY – Nov 30
National Meth Awareness Day – Nov 30
Computer Security Day – Nov 30
Stay Home Because Your Well Day – Nov 30

-- Dec

NATIONAL PIE DAY – Dec 1
NATIONAL EAT A RED APPLE DAY – Dec 1
Bifocals at the Monitor Liberation Day – Dec 1
Day With (Out) Art – Dec 1
Rosa Parks Day – Dec 1
NATIONAL FRITTERS DAY – Dec 2
NATIONAL MUTT DAY – Dec 2
NATIONAL SPECIAL EDUCATION DAY – Dec 2
Rockefeller Tree Lighting – Dec 3
-- Faux Fur Friday – First Friday in Dec
NATIONAL ROOF OVER YOUR HEAD DAY – Dec 3
-- National Rhubarb Vodka Day – First Saturday in Dec
-- Skywarn Recognition Day – First Saturday in Thanksgiving
National Cookie Day – Dec 4
National Dice Day – Dec 4
National Sacher Torte Day – Dec 5
AFL-CIO Day – Dec 5
Bathtub Party Day – Dec 5
international Ninja Day – Dec 5
NATIONAL PAWNBROKERS DAY – Dec 6
NATIONAL MICROWAVE OVEN DAY – Dec 6
NATIONAL GAZPACHO DAY – Dec 6
St. Nicholas Day – Dec 6
NATIONAL MINERS DAY – Dec 6
NATIONAL PEARL HARBOR REMEMBRANCE DAY – Dec 7
NATIONAL COTTON CANDY DAY – Dec 7
NATIONAL BROWNIE DAY – Dec 8
Pretend to be a Time Traveler Day – Dec 8
NATIONAL PASTRY DAY – Dec 9
Weary Willie Day – Dec 9
Dewey Decimal System Day – Dec 10
HUMAN RIGHTS DAY – Dec 10
Nobel Prize Day – Dec 10
NATIONAL NOODLE RING DAY – Dec 11
UNICEF Birthday – Dec 11
NATIONAL AMBROSIA DAY – Dec 12
NATIONAL DING-A-LING DAY – Dec 12
Gingerbread House Day – Dec 12
NATIONAL POINSETTIA DAY – Dec 12
NATIONAL COCOA DAY – Dec 13
NATIONAL VIOLIN DAY – Dec 13

Pick a Pathologist Pal Day – Dec 13
NATIONAL BOUILLABAISSE DAY – Dec 14
National Cupcake/Lemon Cupcake Day – Dec 15
Bill of Rights Day – Dec 15
Cat Herders Day – Dec 15
National Chocolate-covered Anything Day – Dec 16
Barbie and Barney Backlash Day – Dec 16
-- National Ugly Christmas Sweater Day – 2nd Friday in Dec
-- Underdog Day – Third Friday in Dec
NATIONAL MAPLE SYRUP DAY – Dec 17
WRIGHT BROTHERS DAY – Dec 17

NATIONAL ROAST SUCKLING PIG DAY – Dec 18
Answer the Telephone Like Buddy The Elf Day – Dec 18

NATIONAL HARD CANDY DAY – Dec 19
NATIONAL OATMEAL MUFFIN DAY – Dec 19
NATIONAL SANGRIA DAY – Dec 20
Mudd Day – Dec 20
NATIONAL FRENCH FRIED SHRIMP DAY – Dec 21
Crossword Puzzle Day – Dec 21
Humbug Day – Dec 21
Phileas Fogg Win a Wager – Dec 21
Winter Solstice – Dec 21
NATIONAL FLASHLIGHT DAY – Dec 21
National Homeless Persons’ Remembrance Day – Dec 21
Yule – Dec 21
NATIONAL DATE NUT BREAD DAY – Dec 22
Ann & Samantha Day – Dec 22
Forefathers Day – Dec 21
NATIONAL RE-GIFTING DAY – Thursday Before Xmas
NATIONAL PFEFFERNUSSE DAY – Dec 23
NATIONAL ROOTS DAY – Dec 23
Festivus – Dec 23
NATIONAL EGGNOG DAY – Dec 24
Christmas Eve – Dec 24
Chanukah – changes annually
NATIONAL PUMPKIN PIE DAY – Dec 25
A’Phabet Day or No “L” Day – Dec 25
Christmas – Dec 25
NATIONAL CANDY CANE DAY – Dec 26
NATIONAL THANK YOU NOTE DAY – Dec 26
NATIONAL WHINERS DAY – Dec 26
Boxing Day – Dec 26
NATIONAL FRUITCAKE DAY – Dec 27
NATIONAL CHOCOLATE CANDY DAY – Dec 28
NATIONAL CARD PLAYING DAY – Dec 28
Holy Innocents Day – Dec 28
Pledge of Allegiance Day – Dec 28
NATIONAL PEPPER POT DAY – Dec 29
Tick Tock Day – Dec 29
National Bicarbonate of Soda Day – Dec 30
Falling Needles Family Fest Day – Dec 30

No interruptions Day – Dec 31
NATIONAL CHAMPAGNE DAY – Dec 31
Leap Second Time Adjustment Day – Dec 31
Make Up Your Mind Day – Dec 31
NEW YEARS EVE – Dec 31
Universal Hour of Peace Day – Dec 31
